#ifndef TRACTOR_CONVERTER_DEFINES_H
#define TRACTOR_CONVERTER_DEFINES_H



#define TRACTOR_CONVERTER_VERSION "1.0.0"

#define TRACTOR_CONVERTER_STR_HELPER(x) #x
#define TRACTOR_CONVERTER_STR(x) TRACTOR_CONVERTER_STR_HELPER(x)



// For program options.
#define TRACTOR_CONVERTER_DEFAULT_3D_DEFAULT_SCALE 0.195313
#define TRACTOR_CONVERTER_DEFAULT_3D_DEFAULT_SCALE_STR \
  TRACTOR_CONVERTER_STR(TRACTOR_CONVERTER_DEFAULT_3D_DEFAULT_SCALE)

#define TRACTOR_CONVERTER_DEFAULT_C3D_DEFAULT_MATERIAL "body_red"



// For helpers.
#define TRACTOR_CONVERTER_DONT_THROW_ON_FAILURE 0
#define TRACTOR_CONVERTER_THROW_ON_FAILURE 1



#endif // TRACTOR_CONVERTER_DEFINES_H

